// Svelte/meu-app/src/Views/Mainpage/Components/Lista/lista.svelte
<script>

</script>
<main>
    <div class="list-group ">
        <a href="/" class="list-group-item list-group-item-action  bg-dark  active">teste</a>
    
                <div class="list-group-item big-checkbox ">
                    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" />
                    <a href="/" >teste</a>
                </div>
    
    
        <div class="list-group-item list-group-item-action">
            <div class="input-group ">
                <input  type="text" class="form-control" placeholder="Novo item" aria-label="Novo item" aria-describedby="button-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Adiconar</button>
                </div>
            </div>
        </div>
    </div> 
</main>

<!-- 
<div class="list-group ">
    <a href="/" class="list-group-item list-group-item-action  bg-dark  active">teste</a>

            <div className="list-group-item big-checkbox ">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" />
                <a href="/" >teste</a>
            </div>


    <div className="list-group-item list-group-item-action">
        <div className="input-group ">
            <input  type="text" className="form-control" placeholder="Novo item" aria-label="Novo item" aria-describedby="button-addon2" />
            <div className="input-group-append">
                <button className="btn btn-outline-secondary" type="button" id="button-addon2">Adiconar</button>
            </div>
        </div>
    </div>
</div> -->

// React/my-app/src/Views/Mainpage/Components/Lista/index.js
import React from 'react';

export default function Lista(props) {
    return (
        <div class="list-group ">
            <a href="/" className="list-group-item list-group-item-action active">Nome da lista</a>
            <a href="/" className="list-group-item list-group-item-action">Item 2</a>
            <a href="/" className="list-group-item list-group-item-action">Item 3</a>
            <a href="/" className="list-group-item list-group-item-action">Item 4</a>
            
            <div className="list-group-item list-group-item-action">
                <div className="input-group ">
                    <input type="text" className="form-control" placeholder="Novo item" aria-label="Novo item" aria-describedby="button-addon2" />
                    <div className="input-group-append">
                        <button className="btn btn-outline-secondary" type="button" id="button-addon2">Adiconar</button>
                    </div>
                </div>
            </div>
        </div>
    )
}
