// Svelte/meu-app/src/Views/Mainpage/Components/AdicionarLista/adicionarlista.svelte
<main>
    <div class="list-group ">
        <div class="list-group-item">
            <div class="input-group ">
                <input type="text" class="form-control" placeholder="Novo item" aria-label="Novo item" aria-describedby="button-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button"  id="button-addon2">Adicionar</button>
                </div>
            </div>
        </div>
      
    </div>
</main>

// Angular/meuapp/src/app/Views/mainpage/Components/adicionarlista/adicionarlista.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-adicionarlista',
  templateUrl: './adicionarlista.component.html',
})

export class AdicionarlistaComponent implements OnInit {

  @Output() criarLista = new EventEmitter()

  name = ''

  constructor() { }

  ngOnInit(): void {
  }

}



<div class="list-group ">
    <a href="/" class="list-group-item list-group-item-action  bg-dark  active">Adicionar lista</a>


    <div class="list-group-item list-group-item-action">
        <form >
            <div class="input-group ">
                <input/>
                <div class="input-group-append">
                    <button (click)="criarLista.emit('teste')" class="btn btn-outline-secondary" type="button" id="button-addon2">inserir</button>
                </div>
            </div>
        </form>
    </div>
</div>
