// React/my-app/src/Views/Mainpage/index.js
import React, { useState, useEffect, useCallback } from 'react';
import Lista from './Components/Lista';
import MyNavBar from '../../Components/navbar'
import ListaAdicionar from './Components/ListaAdicionar';
import "./index.css"

export default function Mainpage() {
    const [ListasVector, SetListaVector] = useState({
        "teste 1": ["123", "234"],
    }); 
    function addOnList(newItem, key){
        let newList = {};

        for(let i =0; i < Object.keys(ListasVector).length;i++){
            let key = Object.keys(ListasVector)[i];
            newList[key] = ListasVector[key];
        }
        
        let arr = newList[key];
        arr.push(newItem);
        newList[key] = arr;
        return newList;
    }


    function addAList(newListName){
        var newList = {};
        
        for(let i =0; i < Object.keys(ListasVector).length;i++){
            let key = Object.keys(ListasVector)[i];
            newList[key] = ListasVector[key];
        }

        newList[newListName] = [];
        SetListaVector(newList);
    }


    return (
        <div>
            <MyNavBar></MyNavBar>
            <div>
                <div className="container-fluid p-4 testimonial-group" >
                    <div className="row overflow-auto" >
                        {Object.keys(ListasVector).map((key)=>{
                            return (
                                <div className="col-sm-3" key={key} id="widthScroll">
                                    <Lista title={key} itens= {ListasVector[key]} vector={ListasVector} setList={SetListaVector} addList={addOnList}></Lista>
                                </div>
                            )
                        })}
                        
                        <div className="col-sm-3">
                            <ListaAdicionar func={addAList}></ListaAdicionar>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    )
}

// Svelte/meu-app/src/Views/Mainpage/mainpage.svelte
<script>
    import { Col, Container, Row } from 'sveltestrap';
import Lista from './Components/Lista/lista.svelte'
import Nonloggednavbar from '../../Components/NonLoggedNavBar/nonloggednavbar.svelte';
import ListaAdicionar from './Components/AdicionarLista/adicionarlista.svelte'
</script>

<main>
    <div>
        <Nonloggednavbar></Nonloggednavbar>
        <div>
            <div class="container-fluid p-4 testimonial-group" >
                <div class="row overflow-auto" >
                
                            <div class="col-sm-3"id="widthScroll">
                                <Lista></Lista>
                            </div>
                    
                    
                    <div class="col-sm-3">
                        <ListaAdicionar></ListaAdicionar>
                    </div>
                </div>
            </div>
        </div>

    </div>
</main>

<style>

</style>
<!-- 
 <div>
        <MyNavBar></MyNavBar>
        <div>
            <div className="container-fluid p-4 testimonial-group" >
                <div className="row overflow-auto" >
          
                            <div className="col-sm-3"  id="widthScroll">
                                <h1>teste</h1>
                                <Lista></Lista>
                                <Lista title={key} itens= {ListasDeListas[key]} vector={ListasDeListas} setList={SetListaDeLista} addList={addOnList}></Lista>
                            </div>
                    
                    <div className="col-sm-3">
                        <ListaAdicionar func={addAList}></ListaAdicionar>
                    </div>
                </div>
            </div>
        </div>

    </div> -->
