// Vue/meu-app/src/components/nonLoggedNavBar/nonloggednavbar.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Multido</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <form class="form-inline my-2 my-lg-0">
          <ul class="navbar-nav mr-auto">
            <router-link to="/Login"><button class="btn btn-light px-3 mx-3 my-sm-0" type="submit">Cadastre-se</button></router-link>
            <button class="btn btn-secondary px-3 my-sm-0" type="submit">Entrar</button>
          </ul>
        </form>
      </div>
    </nav>
  </div>
</template>
<script>
export default {
    name: "NonLoggedNavBar"
};
</script>

<style>
</style>

// Angular/meuapp/src/app/Components/non-loggednavbar/non-loggednavbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nonnavbar',
  templateUrl: './non-loggednavbar.component.html',
})
export class NonLoggednavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Multido</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a to="/" class="nav-link" href="#">Página inicial <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a to="/Mainpage" class="nav-link" href="#">Perfil</a>
                </li>
            </ul>
            <div class="form-inline my-2 my-lg-0">
               <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Sair</button>
            </div>
        </div>
    </nav>

</div>
