// Svelte/meu-app/src/Views/Mainpage/Components/Lista/Components/Checkitem/checkitem.svelte
<script>
    export let title = "item";
    export let removerMeuItem = function(){};
	let check = false;

</script>

<main>
    <div class="list-group-item big-checkbox ">
        <input bind:checked={check} on:change={(e)=>{e.target.value = check; e.target.indeterminate = false}} on:click={removerMeuItem(title)} class="form-check-input" type="checkbox" value="" id="defaultCheck1" />
        <a href="/" >{title}</a>
    </div>
</main>

// Vue/meu-app/src/Pages/MainPage/Components/Checkitem/checkitem.vue
<template>
    <div className="list-group-item big-checkbox ">
         <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" />
         <a href="/" key={key}>{{name}}</a>
    </div>
</template>
<script>
export default {
    name: "Checkitem",
    props: ['name']
};
</script>

<style>
</style>
