// Vue/meu-app/src/Pages/MainPage/Components/Checklist/Checklist.vue
<template>
  <div className="list-group ">
    <a
      href="/"
      className="list-group-item list-group-item-action  bg-dark  active"
      >{{ title }}</a
    >
    <Checkitem v-for="item in itens" :key="item" v-bind:name="item"></Checkitem>

    <div className="list-group-item list-group-item-action">
      <div className="input-group ">
        <input
          type="text"
          className="form-control"
          placeholder="Novo item"
          aria-label="Novo item"
          aria-describedby="button-addon2"
        />
        <div className="input-group-append">
          <button
            className="btn btn-outline-secondary"
            type="button"
            id="button-addon2"
          >
            Adiconar
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import Checkitem from "../Checkitem/checkitem";
export default {
  name: "Checklist",
  components: {
    Checkitem,
  },

  props: ["title", "itens"],
};
</script>

<style>
</style>

// Angular/meuapp/src/app/Views/mainpage/Components/checklist/checklist.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Lista } from 'src/app/Class/lista';

@Component({
  selector: 'app-checklist',
  templateUrl: './checklist.component.html',
})
export class ChecklistComponent implements OnInit {
   @Input() title = "title";
   @Input() itens = [];

  constructor() { }

  ngOnInit(): void {
  }

}
 
<style>

</style>

<div class="list-group ">
    <a href="/" class="list-group-item list-group-item-action  bg-dark  active">{{title}}</a>


    <app-checklistitem ></app-checklistitem>
    <app-checklistitem ></app-checklistitem>


    <div class="list-group-item list-group-item-action">
        <div class="input-group ">
            <input />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2">Adiconar</button>
            </div>
        </div>
    </div>
</div>
